apiVersion: batch/v1
kind: Job
metadata:
  name: lookup-table
  labels:
    app: lookup-table
spec:
  template:
    metadata:
      labels:
        app: lookup-table
    spec:
      containers:
        - name: lookup-table
          image: abyssnlp/customers-lookup:0.1
          imagePullPolicy: IfNotPresent
      restartPolicy: Never
  backoffLimit: 0
