apiVersion: batch/v1
kind: Job
metadata:
  name: orders-producer
  labels:
    app: orders-producer
spec:
  template:
    metadata:
      labels:
        app: orders-producer
    spec:
      containers:
        - name: orders-producer
          image: abyssnlp/orders-producer:0.1
          imagePullPolicy: IfNotPresent
      restartPolicy: Never
  backoffLimit: 0
